[package]
name = "multipass"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.12.1"
n0-error = "1.0.0"
noq = "1.1.1"
noq-proto = "1.1.1"
rcgen = "0.14.8"
rustls = "0.23.43"
tokio = { version = "1.53.1", features = ["full"] }
tokio-stream = "0.1.19"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
